source 'https://git.coding.net/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'WQView_Example' do
  pod 'WQView', :path => '../'

  target 'WQView_Tests' do
    inherit! :search_paths

    
  end
end
